# Site settings
title: Medema Labs
email: webmaster@medemalabs.com
description: "Medema Labs: Mechanical Design and Manufacturing Software Solutions"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/pub/medemalabs
  - title: github
    url: http://github.com/medemalabs
  - title: envelope
    url: mailto:matt@medemalabs.com

# Postal address (add as many lines as necessary)
address:
  - line: P.O.Box
  - line: Corvallis, OR 97330, USA

# Team names, titles and social links
people:
- name: Matt Campbell
  pic: campbell
  position: CEO, Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Brandon Massoni
  pic: massoni.jpg
  position: Cheift Technical Officer, Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

  
  
# Build settings
markdown: kramdown
permalink: pretty

