# Site settings
title: Medema Labs
email: webmaster@medemalabs.com
description: "Medema Labs: Mechanical Design and Manufacturing Software Solutions"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/pub/rick-kim/30/aa7/a70
  - title: github
    url: http://github.com/y7kim
  - title: envelope
    url: mailto:kim.rick@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: Waterloo St.
  - line: Kitchener, ON N2H3V5

# Team names, titles and social links
people:
- name: Matt Campbell
  pic: campbell
  position: CEO, Found
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Brandon Massoni
  pic: massoni
  position: Cheift Technical Officer, Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

  
  
# Build settings
markdown: kramdown
permalink: pretty

